[package]
name = "graph"
version = "0.1.0"
edition = "2018"

[dependencies]
rand = "0.8.4"
rayon = "1.5.1"
rustc-hash = "1.1.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "digraph_benchmark"
harness = false